### ISSUE TITLE
rotate 90 degrees yaw with camera and pitch is on the wrong axis w/fix

### ISSUE THREAD

**Issue by unmodify** [StanislavPetrovV/Software_3D_engine#3]
Thank you for your videos and making project available. <3

rotate 90 degrees yaw with camera and pitch is on the wrong axis.  Here is a fix.  Collecting Euler angles and applying rotation to camera identity origin

#camera.py
        #add to __init__
                self.anglePitch = 0
		self.angleYaw = 0
		self.angleRoll = 0

	def camera_yaw(self, angle):
		self.angleYaw += angle

	def camera_pitch(self, angle):
		self.anglePitch += angle

	def axiiIdentity(self):
		self.forward = np.array([0, 0, 1, 1])
		self.up = np.array([0, 1, 0, 1])
		self.right = np.array([1, 0, 0, 1])

	def camera_update_axii(self):
		# rotate = rotate_y(self.angleYaw) @ rotate_x(self.anglePitch)
		rotate = rotate_x(self.anglePitch) @ rotate_y(self.angleYaw)   #this concatenation gives right visual
		self.axiiIdentity()
		self.forward = self.forward @ rotate
		self.right = self.right @ rotate
		self.up = self.up @ rotate

	def camera_matrix(self):
		self.camera_update_axii()
		return self.translate_matrix() @ self.rotate_matrix()

**Comment by StanislavPetrovV** [comment]
thanks for the fix, i used your code in camera.py
